Repository HackerN64/HackerSM64, pull requests merged in 2021-12, with the labels that each got.

#161 Make the door lock a part of the key door model to eliminate z-fighting, also reduce z fighting on numbered doors with AUTO_LOD enabled.
  actors/common1.h
  actors/door/geo.inc.c
  actors/door/model.inc.c
Labels: needs console verification

#196 Fixed UNLOCK_FPS strobing
  src/game/game_init.c
Labels: bug

#238 Added WATER_PLUNGE_UPWARP define
  include/config/config_movement.h
  src/game/mario.c
Labels: enhancement, waiting on pull request

#241 added reonucam credit
  README.md
Labels: documentation

#242 Develop/refactor default defines
  .vscode/c_cpp_properties.json
  include/config/config_audio.h
  include/config/config_debug.h
  include/config/config_game.h
  include/config/config_graphics.h
  include/config/config_movement.h
  include/config/config_objects.h
Labels: question, critical

#247 revert air step line to vanilla to fix bitfs scaling platform issue
  src/game/mario_step.c
Labels: critical

#248 Fix stuttering on thin slopes
  src/engine/surface_collision.h
  src/game/mario.c
  src/game/mario_actions_automatic.c
  src/game/mario_actions_cutscene.c
  src/game/mario_actions_submerged.c
  src/game/mario_step.c
Labels: question, needs verification

#255 skip wall offsets < 0
  src/engine/surface_collision.c
Labels: bug

#266 derive margin_radius from radius after capping at 200
  src/engine/surface_collision.c
Labels: bug

#271 Improved movement config documentation related to turning around
  include/config/config_movement.h
  src/game/mario_actions_moving.c
Labels: documentation
