Repository HackerN64/HackerSM64, pull requests merged in 2022-06, with the labels that each got.

#414 Fixed level mesh not updating when building
  Makefile
Labels: bug, high priority, Lighting Engine

#391 Bugfix, refactor, and slightly improve BETTER_REVERB runtime
  include/config/config_audio.h
  src/audio/heap.c
  src/audio/heap.h
  src/audio/synthesis.c
  src/audio/synthesis.h
Labels: bug, performance, waiting on pull request

#426 Fix shindou audio a little bit
  src/audio/heap.c
Labels: bug
