Repository HackerN64/HackerSM64, pull requests merged in 2022-07, with the labels that each got.

#444 Adjust the static surface pool's size automatically per level and add static object collision
  data/behavior_data.c
  include/config/config_world.h
  src/engine/surface_load.c
  src/engine/surface_load.h
  src/game/behavior_actions.h
  src/game/behaviors/ddd_sub.inc.c
  src/game/hud.c
  src/game/object_list_processor.c
  src/game/puppyprint.c
Labels: enhancement

#452 Fixed memory leak between areas from automatic surface pool size
  src/engine/level_script.c
  src/game/area.c
Labels: bug

#454 HackerSM64 2.0.3 Release: Audio Crash
  VERSION.txt
  src/audio/heap.c
  src/audio/heap.h
  src/audio/load.c
Labels: bug, critical

#288 Clean up gotos from find_wall_collisions_from_list
  src/engine/surface_collision.c
Labels: enhancement, needs console verification

#412 Replace unused 0C bank with aglab's / scut's extended 0C bank
  include/config/config_audio.h
  sound/sound_banks/0C.json
  sound/sound_banks/0C_extended_bank.json
Labels: enhancement, medium priority

#440 Delete config_interaction.h
  include/config.h
  include/config/config_interaction.h
  include/config/config_movement.h
Labels: enhancement

#464 Line endings for all text files now forced to \n instead of \r\n
  .gitattributes
Labels: critical
