Repository HackerN64/HackerSM64, pull requests merged in 2022-11, with the labels that each got.

#518 Bugfix: skyboxes access tiles out of range when looking straight down
  src/game/skybox.c
Labels: bug, critical

#522 Add define to disable pitch shifting of Mario sound effects
  include/config/config_audio.h
  include/seq_macros.inc
  sound/sequences/00_sound_player.s
Labels: enhancement

#525 Make warp surfaces use the force parameter if set
  include/config/config_collision.h
  include/surface_terrains.h
  src/game/level_update.c
Labels: enhancement

#526 Bugfix: RCP has gone loud because SOMEONE didn't look at their compiler output
  src/boot/main.c
Labels: bug, critical

#521 Wrap boulder room check under vanilla specific level checks
  src/game/behaviors/boulder.inc.c
Labels: enhancement

#505 Implemented native Gamecube controller support and corresponding emulator hint in ROM header
  asm/rom_header.s
  include/config/config_rom.h
  include/n64/PR/os_cont.h
  include/n64/PR/os_motor.h
  include/sm64.h
  include/types.h
  sm64.ld
  src/game/crash_screen.c
  src/game/game_init.c
  src/game/game_init.h
  src/game/gamecube_controller.c
  src/game/mario.c
  src/game/rumble_init.c
  src/goddard/renderer.c
  src/goddard/renderer.h
Labels: enhancement, needs verification, needs console verification

#528 Disable DISABLE_ALL
  include/config/config_debug.h
Labels: enhancement

#422 Add super slippery surface type
  include/surface_terrains.h
  src/game/mario.c
  src/game/mario_actions_moving.c
Labels: enhancement

#517 HackerSM64 2.0.5
  .vscode/c_cpp_properties.json
  Makefile
  include/rtc.h
  include/types.h
  src/audio/heap.c
  src/engine/math_util.c
  src/engine/math_util.h
  src/engine/surface_collision.c
  src/game/behaviors/boo.inc.c
  src/game/behaviors/hoot.inc.c
  src/game/behaviors/lll_octagonal_rotating_mesh.inc.c
  src/game/behaviors/platform_on_track.inc.c
  src/game/behaviors/spawn_star.inc.c
  src/game/camera.c
  src/game/camera.h
  src/game/macro_special_objects.c
  src/game/skybox.c
Labels: bug, critical
