Repository HackerN64/HackerSM64, pull requests merged in 2022-12, with the labels that each got.

#539 HackerSM64 2.0.6
  Makefile
  src/engine/math_util.c
  src/engine/math_util.h
Labels: bug, high priority

#541 Fix 100 coin stars spawning inside ceilings + being able to spawn multiple 100 coin stars
  src/game/behaviors/sparkle_spawn_star.inc.c
  src/game/interaction.c
  src/game/level_update.c
  src/game/level_update.h
Labels: bug

#548 Bugfix: Save & Quit crashes game
  levels/intro/script.c
Labels: bug, critical

#393 Make JRB mist and DDD objects act-specific.
  include/level_commands.h
  levels/ddd/script.c
  levels/jrb/script.c
  src/engine/level_script.c
  src/game/area.c
  src/game/behaviors/ddd_pole.inc.c
  src/game/behaviors/ddd_sub.inc.c
  src/game/mario_actions_submerged.c
  src/game/moving_texture.c
  src/game/skybox.c
Labels: bug, enhancement
