Repository HackerN64/HackerSM64, pull requests merged in 2022-09, with the labels that each got.

#490 Remove Wiseguy from codeowners file :(
  CODEOWNERS
Labels: critical, monkaS

#465 Sound effect tables now support up to 255 sounds instead of 128
  src/audio/external.c
  src/audio/seqplayer.c
Labels: enhancement

#484 Fix inverted null check in obj_get_model_id
  src/game/object_helpers.c
Labels: bug

#479 Clean up remaining DISABLE_LEVEL_CHECKS ifndefs
  src/game/level_update.c
  src/game/puppycam2.c
Labels: bug

#474 Reverted geo bone
  include/geo_commands.h
  src/engine/geo_layout.c
  src/engine/geo_layout.h
  src/engine/graph_node.c
  src/engine/graph_node.h
  src/game/rendering_graph_node.c
Labels: bug

#494 Revert "Implemented native Gamecube controller support and corresponding emulator hint in ROM header"
  asm/rom_header.s
  include/config/config_rom.h
  include/n64/PR/os_cont.h
  include/n64/PR/os_motor.h
  include/sm64.h
  include/types.h
  sm64.ld
  src/game/crash_screen.c
  src/game/game_init.c
  src/game/game_init.h
  src/game/gamecube_controller.c
  src/game/mario.c
  src/game/rumble_init.c
  src/goddard/renderer.c
  src/goddard/renderer.h
Labels: bug, critical

#499 Clean up a bit of code in file_select.c, fixing copy menu buttons not properly getting deleted when switching pages.
  src/menu/file_select.c
Labels: bug

#439 Simplified lives defines
  include/config/config_game.h
  include/config/config_safeguards.h
  src/game/behaviors/mushroom_1up.inc.c
  src/game/behaviors/yoshi.inc.c
  src/game/hud.c
  src/game/ingame_menu.c
  src/game/level_update.c
  src/game/mario.c
  src/game/mario_actions_cutscene.c
  src/game/save_file.c
  src/game/save_file.h
Labels: enhancement

#497 Bugfix: Memory leak caused by missing pool pop state
  levels/scripts.c
Labels: bug

#462 Added ability to automatically pull unfloader and build for unf debug
  Makefile
  tools/Makefile
  tools/get_latest_unfloader.py
Labels: enhancement, needs verification

#500 Bugfix: Change instant warps to use ints instead of shorts
  include/level_commands.h
  include/surface_terrains.h
  src/engine/level_script.c
  src/game/area.h
Labels: bug, high priority
