Repository HackerN64/HackerSM64, pull requests merged in 2023-06, with the labels that each got.

#631 WDW Denorm Fix
  levels/wdw/areas/1/collision.inc.c
  src/engine/surface_load.c
Labels: bug, critical

#628 added make_patch and flips
  Makefile
  tools/.gitignore
  tools/Flips/Flips.cpp
  tools/Flips/crc32.h
  tools/Flips/divsufsort.h
  tools/Flips/divsufsort_private.h
  tools/Flips/errors
  tools/Flips/flips.h
  tools/Flips/global.h
  tools/Flips/libbps.h
  tools/Flips/libips.h
  tools/Flips/libups.h
  tools/Makefile
Labels: enhancement

#611 Use FillRectangle for shade_screen
  bin/segment2.c
  src/game/ingame_menu.c
  src/game/segment2.h
Labels: performance

#619 Improve BETTER_REVERB runtime by about 15-20% overall
  src/audio/data.c
  src/audio/external.c
  src/audio/heap.c
  src/audio/internal.h
  src/audio/load.c
  src/audio/synthesis.c
  src/audio/synthesis.h
Labels: bug, performance, high priority

#625 Allow envelopes with delay values of 0 on init
  include/seq_macros.inc
  src/audio/effects.c
  src/audio/effects.h
  tools/assemble_sound.py
Labels: enhancement

#623 Increase size/configurability of volume ramping tables
  src/audio/data.c
  src/audio/data.h
  src/audio/synthesis.c
  src/audio/volramping.c.in
Labels: enhancement

#629 Develop/2.1.0 red coin count increase
  README.md
  data/behavior_data.c
  include/object_fields.h
  src/game/behavior_actions.h
  src/game/behaviors/hidden_star.inc.c
  src/game/behaviors/orange_number.inc.c
  src/game/behaviors/red_coin.inc.c
  src/game/behaviors/spawn_star.inc.c
  src/game/ingame_menu.c
  src/game/interaction.c
  src/game/obj_behaviors.c
  src/game/print.h
Labels: enhancement

#633 Disable Stereo Headset Effects and stub out all known code references via define
  include/config/config_audio.h
  include/seq_macros.inc
  src/audio/data.c
  src/audio/data.h
  src/audio/internal.h
  src/audio/playback.c
  src/audio/seqplayer.c
  src/audio/synthesis.c
  src/game/profiling.c
  src/game/sound_init.c
  src/menu/file_select.c
  src/menu/file_select.h
Labels: bug, enhancement, performance

#554 Puppy Camera for 2.1
  enhancements/puppycam_angles.inc.c
  include/text_strings.h.in
  src/engine/math_util.c
  src/engine/math_util.h
  src/game/puppycam2.c
  src/game/puppycam2.h
Labels: high priority

#639 Revert floor sorting optimizations
  src/engine/surface_load.c
Labels: bug, critical

#564 add death on exit course define
  include/config/config_menu.h
  src/game/level_update.c
Labels: enhancement

#532 Update S2DEX Text Engine to latest version; fix build issues
  Makefile
  actors/group0.c
  sm64.ld
  src/game/area.c
  src/s2d_engine/Makefile
  src/s2d_engine/f3d_draw.c
  src/s2d_engine/fonts/ifunny.c
  src/s2d_engine/fonts/ifunny.h
  src/s2d_engine/fonts/newsm64.c
  src/s2d_engine/fonts/newsm64.h
  src/s2d_engine/init.c
  src/s2d_engine/init.h
  src/s2d_engine/mtx.c
  src/s2d_engine/s2d_buffer.c
  src/s2d_engine/s2d_config.h
  src/s2d_engine/s2d_draw.c
  src/s2d_engine/s2d_draw.h
  src/s2d_engine/s2d_engine.h
  src/s2d_engine/s2d_error.c
  src/s2d_engine/s2d_optimized.c
  src/s2d_engine/s2d_optimized.h
  src/s2d_engine/s2d_parse.c
  src/s2d_engine/x86_testing_ground/a.out
  src/s2d_engine/x86_testing_ground/atoi.c
Labels: bug, enhancement

#590 Culling improvements + GRAPH_RENDER_INVISIBLE check change
  include/config/config_graphics.h
  src/engine/geo_layout.c
  src/engine/graph_node.c
  src/engine/graph_node.h
  src/game/rendering_graph_node.c
Labels: enhancement

#646 convert mapPacker.py to use `nm`
  Makefile
  tools/mapPacker.py
Labels: enhancement

#647 Get rid of all inline asm
  asm/round.s
  sm64.ld
  src/engine/math_util.h
Labels: questionable, needs verification, performance

#545 IPL3 documentation; undefined_syms.txt finally deleted
  Makefile
  asm/ipl3.s
  include/n64/PR/ultratypes.h
  sm64.ld
  undefined_syms.txt
Labels: enhancement, questionable

#591 Add SET_ECHO level script command + minor BETTER_REVERB refactoring
  include/config/config_audio.h
  include/level_commands.h
  src/audio/data.c
  src/audio/data.h
  src/audio/external.c
  src/audio/external.h
  src/audio/heap.c
  src/audio/heap.h
  src/audio/synthesis.c
  src/audio/synthesis.h
  src/engine/level_script.c
  src/game/area.c
  src/game/area.h
  src/game/level_update.c
  src/game/puppyprint.c
  src/game/puppyprint.h
Labels: enhancement

#649 Slice BETTER_REVERB memory requirements in half
  src/audio/synthesis.c
  src/audio/synthesis.h
Labels: enhancement, performance

#648 Dynamic collision fixes + actual OR_LONG
  data/behavior_data.c
  src/engine/behavior_script.c
  src/engine/surface_load.c
Labels: bug, enhancement
