Repository HackerN64/HackerSM64, pull requests merged in 2023-09, with the labels that each got.

#668 Fixed broken Makefile
  Makefile
Labels: bug

#672 Bugfix: Selecting headset audio and then disabling stereo headset effects define leads to game crash in sound select
  src/audio/external.h
  src/game/save_file.c
  src/game/sound_init.c
  src/game/sound_init.h
  src/menu/file_select.c
  src/menu/file_select.h
Labels: bug

#674 Add make rebuildtools
  Makefile
  tools/Makefile
Labels: enhancement

#670 Look for shared baserom directory using XDG_DATA_DIR instead of polluting the home directory
  extract_assets.py
Labels: enhancement

#678 Fix typo describing BETTER_REVERB parameters
  src/audio/data.c
Labels: documentation

#671 Add functional changes to inertia to support only specific directions specified in the config
  include/config/config_movement.h
  src/game/platform_displacement.c
Labels: enhancement

#636 Rotate envmaps to be consistent with vanilla
  actors/mario/model.inc.c
  actors/mario_cap/model.inc.c
  actors/water_ring/model.inc.c
  extract_assets.py
  include/config/config_graphics.h
  src/game/rendering_graph_node.c
  tools/n64graphics.c
Labels: critical

#666 Important Culling Fixes
  include/config/config_graphics.h
  src/game/rendering_graph_node.c
Labels: bug, critical

#507 Added config option for previewable blue coins
  include/config/config_objects.h
  src/game/behaviors/blue_coin.inc.c
Labels: enhancement, subjective

#685 Add missing JRB vanilla level check
  src/game/behaviors/spawn_star.inc.c
Labels: bug

#687 fix tile scrolled light materials
  tools/fixlights.py
Labels: critical, needs verification

#688 Fix STAR_DANCE_USES_STARS_MODEL define
  src/game/interaction.c
  src/game/level_update.c
  src/game/mario_actions_cutscene.c
  src/game/mario_actions_cutscene.h
Labels: bug

#689 Track whether the RCP hang timer has started to prevent double setting
  src/boot/main.c
  src/game/main.h
Labels: bug, critical

#595 4 controllers support + osContCh optimization
  README.md
  asm/rom_header.s
  include/config/config_rom.h
  include/n64/PR/os_cont.h
  include/types.h
  sm64.ld
  src/boot/main.c
  src/game/behaviors/hoot.inc.c
  src/game/game_init.c
  src/game/game_init.h
  src/game/gamecube_controller.c
  src/game/ingame_menu.c
  src/game/mario.c
  src/game/obj_behaviors.c
  src/menu/file_select.c
  src/menu/star_select.c
  src/menu/title_screen.c
Labels: enhancement, performance

#698 remap scale with fov and avoid copy when world scale is 1
  src/game/rendering_graph_node.c
Labels: bug, high priority

#696 Small texture type fix for the cannon
  src/game/screen_transition.c
Labels: bug

#700 Fix camera issues with NON_STOP_STARS
  src/game/camera.c
Labels: bug

#702 Remove sharp transitions
  bin/segment2.c
  include/config/config_graphics.h
  src/game/screen_transition.c
  textures/segment2/transition_bowser_half.i8.png
  textures/segment2/transition_circle_half.i8.png
  textures/segment2/transition_mario.i8.png
  textures/segment2/transition_star_half.i8.png
Labels: bug

#708 removed extraneous mat stack index decrement in geo_process_camera
  src/game/rendering_graph_node.c
Labels: bug, critical, high priority, monkaS

#711 rename flips src dir
  tools/FlipsSrc/Flips.cpp
  tools/FlipsSrc/Flips.h
  tools/Makefile
Labels: bug, critical

#713 v2.1.2
  VERSION.txt
Labels: documentation

#714 Release: v2.1.2
  VERSION.txt
  src/game/behaviors/intro_scene.inc.c
  tools/FlipsSrc/Flips.cpp
  tools/FlipsSrc/Flips.h
  tools/Makefile
Labels: bug, critical
