Repository HackerN64/HackerSM64, pull requests merged in 2023-03, with the labels that each got.

#580 Small improvements to object loading within rooms
  include/config/config_game.h
  src/engine/behavior_script.c
  src/engine/surface_collision.c
  src/engine/surface_collision.h
  src/game/object_helpers.c
  src/game/object_helpers.h
Labels: enhancement, performance, low priority

#579 Add define for wiping save data if existing save data from vanilla or another hack exists
  include/config/config_rom.h
  src/game/save_file.c
Labels: enhancement

#589 Bugfix: Fix reference to missing function
  src/game/object_helpers.c
  src/game/object_helpers.h
Labels: bug, critical

#593 Frustratio funny fix 2
  bin/segment2.c
Labels: bug, critical

#596 Frustratio funny fix part 3
  bin/segment2.c
Labels: bug, critical

#362 2.1.0 Puppyprint Changes
  bin/segment2.c
  include/config/config_debug.h
  include/config/config_safeguards.h
  include/segment_symbols.h
  src/audio/external.c
  src/audio/heap.c
  src/audio/heap.h
  src/audio/internal.h
  src/audio/seqplayer.c
  src/audio/synthesis.c
  src/boot/memory.c
  src/buffers/buffers.h
  src/engine/level_script.c
  src/engine/math_util.c
  src/engine/surface_collision.c
  src/engine/surface_load.c
  src/game/area.c
  src/game/camera.c
  src/game/crash_screen.c
  src/game/fasttext.c
  src/game/game_init.c
  src/game/hud.c
  src/game/level_update.c
  src/game/object_list_processor.c
  src/game/profiling.c
  src/game/profiling.h
  src/game/puppycam2.c
  src/game/puppyprint.c
  src/game/puppyprint.h
  src/game/segment2.h
  src/game/sound_init.c
  textures/segment2/custom_text.i4.png
  textures/segment2/custom_text2.i4.png
  textures/segment2/custom_text2.ia4.png
  textures/segment2/custom_text3.i4.png
  textures/segment2/custom_text4.i4.png
  tools/n64graphics.c
Labels: enhancement, high priority

#605 Invert skip room proc obj
  include/config/config_debug.h
  include/object_constants.h
  src/engine/behavior_script.c
Labels: critical

#602 Add lightweight configuration settings to BETTER_REVERB
  src/audio/data.c
  src/audio/heap.c
  src/audio/internal.h
  src/audio/synthesis.c
  src/audio/synthesis.h
  src/game/puppyprint.c
Labels: enhancement, performance

#601 Fix rooms and doors
  data/behavior_data.c
  levels/castle_inside/areas/1/room.inc.c
  src/engine/behavior_script.c
  src/engine/surface_collision.c
  src/game/behaviors/door.inc.c
  src/game/object_helpers.c
  src/game/object_helpers.h
  src/game/object_list_processor.c
  src/game/object_list_processor.h
Labels: critical
