Repository HackerN64/HackerSM64, pull requests merged in 2023-12, with the labels that each got.

#732 Add control command format for dialog strings
  include/macros.h
  src/game/ingame_menu.c
  src/game/ingame_menu.h
  src/game/puppycam2.c
  src/menu/file_select.c
  src/menu/star_select.c
  text/define_courses.inc.c
  text/define_text.inc.c
  text/us/dialogs.h
Labels: enhancement

#731 Update Dockerfile to Ubuntu 22.04 as 18.04 is EOL
  Dockerfile
Labels: bug

#730 Add DEBUG_ASSERTIONS define and enable it by default
  include/config/config_debug.h
  include/config/config_safeguards.h
  src/game/debug.h
Labels: enhancement, high priority

#722 Add relevant model ID asserts to level script load commands
  src/engine/level_script.c
Labels: enhancement

#723 Add file select skip define
  include/config/config_cutscenes.h
  levels/menu/script.c
Labels: enhancement

#735 Remove OBJECTS_REJ and clean up core render func (By Fazana)
  include/config/config_safeguards.h
  include/object_constants.h
  include/types.h
  src/engine/behavior_script.c
  src/engine/graph_node.h
  src/game/debug_box.c
  src/game/debug_box.h
  src/game/game_init.c
  src/game/rendering_graph_node.c
  src/game/rendering_graph_node.h
  src/game/spawn_object.c
Labels: bug, enhancement

#566 Math util cleanup
  src/engine/colors.c
  src/engine/colors.h
  src/engine/math_util.c
  src/engine/math_util.h
  src/engine/surface_load.c
  src/game/behaviors/chain_chomp.inc.c
  src/game/behaviors/hoot.inc.c
  src/game/behaviors/intro_peach.inc.c
  src/game/behaviors/spawn_star.inc.c
  src/game/camera.c
  src/game/gamecube_controller.c
  src/game/mario.c
  src/game/mario_actions_moving.c
  src/game/mario_actions_submerged.c
  src/game/object_helpers.c
  src/game/puppycam2.c
  src/game/rendering_graph_node.c
  src/game/skybox.c
Labels: enhancement, performance

#724 Cache master displaylist on "hot" code paths
  src/boot/memory.c
  src/game/debug_box.c
  src/game/game_init.c
  src/game/hud.c
  src/game/puppycam2.c
  src/game/puppyprint.c
  src/game/screen_transition.c
Labels: needs console verification, performance

#710 Synthesis Audio Cleanup
  src/audio/effects.c
  src/audio/external.c
  src/audio/internal.h
  src/audio/playback.c
  src/audio/seqplayer.c
  src/audio/synthesis.c
Labels: documentation, enhancement, performance, monkaS

#736 Remove remainder of Puppylights code
  README.md
  include/level_commands.h
  include/object_fields.h
  include/types.h
  src/boot/main.c
  src/engine/behavior_script.c
  src/engine/level_script.c
  src/game/behavior_actions.c
  src/game/level_update.c
  src/game/obj_behaviors.c
  src/game/obj_behaviors_2.c
  src/game/object_helpers.c
  src/game/object_list_processor.c
  src/game/puppylights.c
  src/game/puppylights.h
  src/game/spawn_object.c
Labels: bug

#739 Define changes for transitions, two bug fixes
  include/config/config_graphics.h
  src/game/area.c
  src/game/level_update.c
  src/game/screen_transition.c
  src/game/screen_transition.h
Labels: bug

#744 Optimize BETTER_REVERB lightweight by an additional ~20% CPU, while also cutting memory requirements for it by ~30%
  src/audio/data.c
  src/audio/synthesis.c
  src/audio/synthesis.h
Labels: performance
