Repository HackerN64/HackerSM64, pull requests merged in 2023-01, with the labels that each got.

#552 Add Spanish translation 🇪🇸
  Makefile.split
  README.md
  bin/segment2.c
  bin/translation_es.c
  include/config/config_game.h
  include/config/config_safeguards.h
  include/segment_symbols.h
  levels/menu/header.h
  levels/menu/leveldata.c
  levels/menu/main_menu_seg7.nivel_upper.rgba16.png
  sm64.ld
  src/game/area.c
  src/game/hud.c
  src/game/ingame_menu.c
  src/game/ingame_menu.h
  src/game/level_update.c
  src/game/puppycam2.c
  src/menu/file_select.c
  src/menu/star_select.c
  text/es/courses.h
  text/es/dialogs.h
Labels: enhancement

#557 Remove GRAPH_NODE_TYPE_FUNCTIONAL + add GeoProcessJumpTable.
  include/config/config_graphics.h
  src/engine/graph_node.c
  src/engine/graph_node.h
  src/game/area.c
  src/game/rendering_graph_node.c
Labels: bug, enhancement, performance

#569 Fix huge stack allocation in surface loading functions
  src/engine/surface_load.c
Labels: monkaS

#425 Added (emu-only) RCVI hack.
  include/config/config_rom.h
  src/audio/synthesis.c
  src/boot/main.c
  src/game/main.h
Labels: enhancement, low priority

#527 Increase max number of concurrent layers and channels
  src/audio/internal.h
Labels: enhancement

#530 Vibrato Optimizations
  sound/sequences/00_sound_player.s
  src/audio/effects.c
  src/audio/effects.h
  src/audio/internal.h
  src/audio/playback.c
  src/audio/seqplayer.c
Labels: enhancement, performance

#573 Bugfix: Stack sizes moved to `game/main.h`
  src/buffers/buffers.h
  src/game/crash_screen.c
  src/game/main.h
Labels: bug, critical

#508 Add support for preset options to be used with BETTER_REVERB
  include/config/config_audio.h
  include/level_commands.h
  levels/ending/script.c
  levels/intro/script.c
  levels/menu/script.c
  src/audio/data.c
  src/audio/data.h
  src/audio/external.c
  src/audio/external.h
  src/audio/heap.c
  src/audio/heap.h
  src/audio/internal.h
  src/audio/load.c
  src/audio/port_eu.c
  src/audio/port_sh.c
  src/audio/synthesis.c
  src/audio/synthesis.h
  src/audio/synthesis_sh.c
  src/engine/level_script.c
  src/game/area.c
  src/game/area.h
  src/game/level_update.c
  src/game/sound_init.c
  src/hvqm/hvqm.c
  src/menu/title_screen.c
Labels: bug, enhancement, performance

#575 Bugfix: Prevent UB that can happen when using more than 64 total soundbanks
  src/audio/data.h
  src/audio/heap.c
  src/audio/heap.h
  src/audio/load.c
  src/audio/load_sh.c
Labels: bug

#574 Update macros.h + allow ALIGN macros to be used anywhere
  include/ique/PR/region.h
  include/macros.h
  include/n64/PR/region.h
  src/audio/load.c
  src/audio/load_sh.c
  src/audio/synthesis.c
  src/audio/synthesis.h
  src/audio/synthesis_sh.c
  src/boot/memory.c
  src/buffers/buffers.c
  src/engine/math_util.c
  src/game/insn_disasm.c
  src/game/main.h
  src/game/save_file.c
  src/goddard/renderer.c
Labels: enhancement
