Repository HackerN64/HackerSM64, pull requests merged in 2024-03, with the labels that each got.

#769 Fix objects using throwmatrix having incorrect rotation when paused
  src/game/obj_behaviors.c
  src/game/rendering_graph_node.c
Labels: enhancement

#740 Toggle the default status of a few defines to avoid confusing new people
  include/config/config_graphics.h
  include/config/config_menu.h
  include/config/config_movement.h
  include/config/config_objects.h
Labels: subjective

#770 A few various Puppyprint bugfixes
  bin/segment2.c
  src/game/fasttext.c
  src/game/puppyprint.c
Labels: bug
