Repository HackerN64/HackerSM64, pull requests merged in 2024-05, with the labels that each got.

#788 Remove destination warp node requirement
  src/engine/level_script.c
  src/game/area.c
  src/game/area.h
  src/game/level_update.c
Labels: enhancement, high priority

#791 Use G_TF_POINT on 3D billboard numbers
  bin/segment2.c
Labels: enhancement

#787 Bugfix: Blue coin duplication
  src/game/behaviors/blue_coin.inc.c
Labels: bug

#799 Add mips64-none-elf- to automatically detected prefixes
  Makefile
Labels: enhancement
