Repository HackerN64/HackerSM64, pull requests merged in 2024-02, with the labels that each got.

#762 Fix wall sidling with negative speed.
  src/game/mario_actions_moving.c
Labels: bug

#746 Fix floating point crash with pitch bend table + various audio optimizations
  include/seq_macros.inc
  sound/sequences/00_sound_player.s
  src/audio/data.c
  src/audio/data.h
  src/audio/effects.c
  src/audio/external.c
  src/audio/heap.c
  src/audio/load.c
  src/audio/load.h
  src/audio/load_sh.c
  src/audio/seqplayer.c
  src/audio/synthesis.c
Labels: bug, critical, performance

#766 Fixed bugs relating to objects dying in lava
  src/game/behaviors/coin.inc.c
  src/game/behaviors/moving_coin.inc.c
  src/game/obj_behaviors.h
  src/game/obj_behaviors_2.c
  src/game/object_helpers.c
Labels: bug, enhancement

#745 Add `-falign-functions=32` to makefile flags
  Makefile
Labels: questionable, needs console verification, performance, high priority

#771 Fix automatic libpl cloning
  Makefile
Labels: bug
