Repository HackerN64/HackerSM64, pull requests merged in 2024-04, with the labels that each got.

#780 Fix fast64 exports due to it exporting macro object data
  include/level_commands.h
  include/types.h
Labels: bug, critical

#781 Bugfix: Fix Mario's model to use prim instead of envcolor for RGB
  actors/mario/model.inc.c
Labels: bug, critical, Lighting Engine

#782 Label unlabelled audio func (func_80321080 to stop_secondary_music)
  src/audio/external.c
  src/audio/external.h
  src/game/behaviors/bbh_merry_go_round.inc.c
  src/game/behaviors/piranha_plant.inc.c
  src/game/sound_init.c
Labels: enhancement

#784 Change compression type to yay0 and ignore .inc.c files in most directories
  Makefile
  lib/librtc.a
  sm64.ld
Labels: high priority

#776 Platform Displacement 2.1
  data/behavior_data.c
  include/config/config_movement.h
  include/object_constants.h
  src/game/behaviors/bowser.inc.c
  src/game/behaviors/tilting_inverted_pyramid.inc.c
  src/game/platform_displacement.c
  src/game/platform_displacement.h
Labels: bug, performance

#785 Add support for a user-defined config_local.h file
  .gitignore
  include/config.h
Labels: enhancement
