Repository HackerN64/HackerSM64, pull requests merged in 2024-01, with the labels that each got.

#748 Fix silhouette occlusion layers rendering twice
  src/game/rendering_graph_node.c
Labels: bug, critical

#742 Fix Boo's Accelerating Upwards During Textbox (Vanilla Bug)
  src/game/behaviors/boo.inc.c
Labels: bug, low priority, vanilla

#719 Added lighting engine by Wiseguy
  README.lighting-engine.md
  README.md
  actors/breakable_box/model.inc.c
  actors/bully/model.inc.c
  actors/goomba/model.inc.c
  actors/group0.h
  actors/mario/geo.inc.c
  actors/mario/geo_header.h
  actors/mario/model.inc.c
  actors/snowman/model.inc.c
  actors/water_ring/model.inc.c
  actors/white_particle/model.inc.c
  actors/white_particle_small/model.inc.c
  data/behavior_data.c
  include/config/config_debug.h
  include/config/config_safeguards.h
  include/geo_commands.h
  include/n64/PR/gbi.h
  include/object_constants.h
  include/object_fields.h
  include/point_lights.h
  levels/level_defines.h
  levels/lighting_engine_demo/area_1/collision.inc.c
  levels/lighting_engine_demo/area_1/geo.inc.c
  levels/lighting_engine_demo/area_1/macro.inc.c
  levels/lighting_engine_demo/area_1/spline.inc.c
  levels/lighting_engine_demo/geo.c
  levels/lighting_engine_demo/geo.inc.c
  levels/lighting_engine_demo/header.h
  levels/lighting_engine_demo/header.inc.h
  levels/lighting_engine_demo/leveldata.c
  levels/lighting_engine_demo/leveldata.inc.c
  levels/lighting_engine_demo/model.inc.c
  levels/lighting_engine_demo/script.c
  levels/lighting_engine_demo/src_data/checkerboard.png
  levels/lighting_engine_demo/src_data/stripes.png
  levels/lighting_engine_demo/src_data/testlevel.blend
  src/engine/behavior_script.c
  src/engine/geo_layout.c
  src/engine/geo_layout.h
  src/engine/graph_node.c
  src/engine/graph_node.h
  src/engine/level_script.c
  src/game/camera.c
  src/game/game_init.c
  src/game/rendering_graph_node.c
Labels: Lighting Engine

#715 Fix weird text on Project64 GLideN64
  bin/segment2.c
Labels: bug, needs verification, needs console verification

#749 Added a define for slope fix
  include/config/config_movement.h
  src/game/mario_actions_moving.c
Labels: enhancement

#755 Release: v2.1.3
  Dockerfile
  VERSION.txt
  bin/segment2.c
  bin/title_screen_bg.c
  include/config/config_debug.h
  include/config/config_game.h
  include/config/config_graphics.h
  include/config/config_safeguards.h
  include/geo_commands.h
  levels/intro/geo.c
  src/audio/synthesis.c
  src/engine/geo_layout.c
  src/engine/level_script.c
  src/game/area.c
  src/game/behaviors/boo.inc.c
  src/game/crash_screen.c
  src/game/debug.h
  src/game/ingame_menu.c
  src/game/level_update.c
  src/game/rendering_graph_node.c
  src/game/rumble_init.c
  src/game/screen_transition.c
  src/game/screen_transition.h
  src/menu/intro_geo.c
  src/menu/intro_geo.h
Labels: bug, enhancement, performance, high priority

#757 Merge HackerSM64 2.1.3 release into 2.2.0
  Dockerfile
  VERSION.txt
  bin/segment2.c
  bin/title_screen_bg.c
  include/config/config_debug.h
  include/config/config_game.h
  include/config/config_graphics.h
  include/config/config_safeguards.h
  include/geo_commands.h
  levels/intro/geo.c
  src/audio/synthesis.c
  src/engine/geo_layout.c
  src/engine/level_script.c
  src/game/area.c
  src/game/behaviors/boo.inc.c
  src/game/crash_screen.c
  src/game/debug.h
  src/game/ingame_menu.c
  src/game/level_update.c
  src/game/rendering_graph_node.c
  src/game/rumble_init.c
  src/game/screen_transition.c
  src/game/screen_transition.h
  src/menu/intro_geo.c
  src/menu/intro_geo.h
Labels: bug, enhancement, critical

#758 Merge HackerSM64 2.1.3 release into 3.0.0
  Dockerfile
  VERSION.txt
  bin/segment2.c
  bin/title_screen_bg.c
  include/config/config_debug.h
  include/config/config_game.h
  include/config/config_graphics.h
  include/config/config_safeguards.h
  include/geo_commands.h
  levels/intro/geo.c
  src/audio/synthesis.c
  src/engine/geo_layout.c
  src/engine/level_script.c
  src/game/area.c
  src/game/behaviors/boo.inc.c
  src/game/crash_screen.c
  src/game/debug.h
  src/game/ingame_menu.c
  src/game/level_update.c
  src/game/rendering_graph_node.c
  src/game/rumble_init.c
  src/game/screen_transition.c
  src/game/screen_transition.h
  src/menu/intro_geo.c
  src/menu/intro_geo.h
Labels: bug, enhancement, critical
