Repository HackerN64/HackerSM64, pull requests merged in 2024-09, with the labels that each got.

#825 Add Fast64 repo settings file (fast64.json)
  fast64.json
Labels: high priority, needs fast64 integration

#821 Add Arthurtilly to the CODEOWNERS file
  CODEOWNERS
Labels: bug, questionable

#795 Update to newest UNF (d5f2ad100b76e372036453f8d25f9b6fbbbd2d1a) (November 22, 2023)
  Makefile
  src/usb/debug.c
  src/usb/debug.h
  src/usb/usb.c
  src/usb/usb.h
  tools/get_latest_unfloader.py
Labels: enhancement, help wanted, needs verification, needs console verification

#832 Dialogs in dialogs.h no longer have to be in order
  text/define_text.inc.c
Labels: enhancement

#704 reset adjacent rooms when loading a new area
  src/game/area.c
Labels: bug, do not merge, needs verification, vanilla

#839 Fix lighting engine by removing duplicate setup_global_light call
  src/game/rendering_graph_node.c
Labels: bug, critical, Lighting Engine
