Repository HackerN64/HackerSM64, pull requests merged in 2024-07, with the labels that each got.

#802 fixlights: added support for ripgrep
  tools/fixlights.py
Labels: enhancement

#800 Added support for windows MinGW build
  extract_assets.py
  sm64.ld
  tools/FlipsSrc/Flips.h
  tools/Makefile
  tools/armips.cpp
  tools/filesizer.c
  tools/fixlights.py
  tools/n64graphics.c
Labels: enhancement

#809 Pressing L in debug fly mode heals Mario
  src/game/mario_actions_cutscene.c
Labels: enhancement

#808 Improve DEATH_ON_EXIT_COURSE define
  src/game/level_update.c
Labels: enhancement

#801 EASIER_LONG_JUMPS: only long jump with A+Z while running
  src/game/mario_actions_airborne.c
  src/game/mario_actions_moving.c
Labels: bug

#804 Bugfix: Missed purging of debug box flags that no longer exist in Puppycam
  src/game/puppycam2.c
Labels: bug

#805 Bugfix: Surfaces not able to be placed at the beginning of a partition
  src/engine/surface_load.c
Labels: bug, critical

#811 Fixed audiofile warnings
  tools/audiofile/audiofile.cpp
Labels: bug, questionable, high priority
