Repository HackerN64/HackerSM64, pull requests merged in 2025-07, with the labels that each got.

#883 Move all music samples to instruments folder and add instrument compatibility tables for legacy and Refresh 16
  .gitignore
  assets.json
  sound/sound_banks/14_piranha_music_box.json
  sound/sound_banks/16_course_start.json
  sound/sound_banks/1D_bowser_organ.json
  tools/assemble_sound.py
Labels: enhancement, cleanup

#850 Add new GZIP DEFLATE decompressor/compressor
  Makefile
  compression/gziprules.mk
  include/gzip.h
  sm64.ld
  src/boot/deflate/common_defs.h
  src/boot/deflate/decompress_template.h
  src/boot/deflate/deflate_constants.h
  src/boot/deflate/deflate_decompress.c
  src/boot/deflate/lib_common.h
  src/boot/deflate/libdeflate.h
  src/boot/memory.c
  src/libz/adler32.c
  src/libz/gzip.c
  src/libz/infback.c
  src/libz/inffast.c
  src/libz/inffast.h
  src/libz/inffixed.h
  src/libz/inflate.c
  src/libz/inflate.h
  src/libz/inftrees.c
  src/libz/inftrees.h
  src/libz/zconf.h
  src/libz/zlib.h
  src/libz/zutil.c
  src/libz/zutil.h
  tools/.gitignore
  tools/Makefile
  tools/deflatepack.c
  tools/libdeflate/bt_matchfinder.h
  tools/libdeflate/common_defs.h
  tools/libdeflate/cpu_features_common.h
  tools/libdeflate/deflate_compress.c
  tools/libdeflate/deflate_compress.h
  tools/libdeflate/deflate_constants.h
  tools/libdeflate/hc_matchfinder.h
  tools/libdeflate/ht_matchfinder.h
  tools/libdeflate/lib_common.h
  tools/libdeflate/libdeflate.h
  tools/libdeflate/matchfinder_common.h
  tools/libdeflate/utils.c
  tools/libdeflate/x86/cpu_features.c
  tools/libdeflate/x86/cpu_features.h
  tools/libdeflate/x86/matchfinder_impl.h
Labels: enhancement, performance

#895 Fix deflate warnings for the last time hopefully
  src/boot/deflate/decompress_template.h
Labels: bug
