Repository HackerN64/HackerSM64, pull requests merged in 2025-01, with the labels that each got.

#854 Add support for building on ARM64 MacOS
  .gitignore
  Makefile
  sm64.ld
  tools/Makefile
  tools/filesizer.c
  tools/lz4hc.c
  tools/mips64-elf-ld-arm
Labels: enhancement

#855 Bugfix: Sign range half of what it was in vanilla
  src/game/interaction.c
  tools/lz4tpack.c
Labels: bug

#844 Bugfix (Vanilla): Warping to cake screen in area other than Area 1 crashes the game
  src/game/area.c
Labels: bug, vanilla

#857 Add support for variadic debug assertions
  src/audio/synthesis.c
  src/engine/level_script.c
  src/game/crash_screen.c
  src/game/debug.c
  src/game/debug.h
  src/game/level_update.c
  src/game/object_list_processor.c
Labels: documentation, enhancement
