Repository HackerN64/HackerSM64, pull requests merged in 2025-02, with the labels that each got.

#862 Fix chuckya grab escape
  src/game/object_helpers.c
Labels: bug, critical, needs verification, needs console verification, HOW, monkaS, subjective, vanilla, blocker

#865 Fix incorrectly labeled JP vanilla dialog
  text/jp/dialogs.h
Labels: bug, help wanted, critical, needs verification, needs console verification, HOW, high priority, monkaS, subjective, vanilla, blocker

#864 Small and quick optimisations to vanilla text printing
  bin/segment2.c
  src/game/hud.c
  src/game/ingame_menu.c
  src/game/print.c
Labels: performance

#868 Clean up and simplify emutest.c, and change instant input to a whitelist
  asm/emux.s
  asm/pj64_get_count_factor_asm.s
  include/config/config_graphics.h
  sm64.ld
  src/boot/main.c
  src/game/emutest.c
  src/game/emutest.h
  src/game/game_init.c
  src/game/rendering_graph_node.c
Labels: needs console verification, monkaS, cleanup

#869 make skyboxes easier to define
  include/geo_commands.h
  include/segment_symbols.h
  include/skyboxes.h
  sm64.ld
  src/game/skybox.c
Labels: enhancement, cleanup

#870 Fixed make patch
  Makefile
Labels: bug
